ALTER TABLE aircraft ADD COLUMN mtow REAL;

ALTER TABLE cost_types ADD COLUMN ground REAL NOT NULL DEFAULT 0;
ALTER TABLE cost_types ADD COLUMN insurance REAL NOT NULL DEFAULT 0;
ALTER TABLE cost_types ADD COLUMN equipment REAL NOT NULL DEFAULT 0;
ALTER TABLE cost_types ADD COLUMN catering REAL NOT NULL DEFAULT 0;